#+AUTHOR: Claudiu
#+HUGO_BASE_DIR: ../
#+LANGUAGE: ro
#+EXCLUDE_TAGS: noexport

#+BEGIN_SRC emacs-lisp :eval yes :results silent
  (load-file "func.el")
  (set-yearly-totals)
#+END_SRC

* Index
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: _index
:EXPORT_TITLE: știri din spațiu
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :fractions false
:END:

** Rachete, astronauți și sonde interplanetare
Siteul de față reprezintă o colecție personală de materiale, articole și notițe (mai mult sau mai puțin structurate) despre explorarea spațiului cosmic, adusă frecvent la zi și mereu extinsă, cu un accent pe rachete și lansări orbitale.

Știrile sunt grupate în Buletine Cosmice, distribuit sub formă de [[https://buletin.parsec.ro/][newsletter]] sau [[https://buletin.parsec.ro/notes][blog]].

** Cele mai recente lansări orbitale

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-last-10 gcatdata 0 2 3 5 6 8 12 13)
#+END_SRC

** Lansări orbitale

+ Lansări orbitale din [[/y/2023][anul curent]];
+ [[/y/total][Statistici generale]];
+ Statistici anuale: [[/y/2022][2022]], [[/y/2021][2021]], [[/y/2020][2020]], [[/y/2019][2019]], [[/y/2018][2018]], [[/y/2017][2017]], [[/y/2016][2016]], [[/y/2015][2015]], [[/y/2014][2014]], [[/y/2013][2013]], [[/y/2012][2012]], [[/y/2011][2011]], [[/y/2010][2010]], [[/y/2009][2009]], [[/y/2008][2008]], [[/y/2007][2007]], [[/y/2006][2006]], [[/y/2005][2005]], [[/y/2004][2004]], [[/y/2003][2003]], [[/y/2002][2002]], [[/y/2001][2001]], [[/y/2000][2000]], [[/y/1999][1999]], [[/y/1998][1998]], [[/y/1997][1997]], [[/y/1996][1996]], [[/y/1995][1995]], [[/y/1994][1994]], [[/y/1993][1993]], [[/y/1992][1992]], [[/y/1991][1991]], [[/y/1990][1990]], [[/y/1989][1989]], [[/y/1988][1988]], [[/y/1987][1987]], [[/y/1986][1986]], [[/y/1985][1985]], [[/y/1984][1984]], [[/y/1983][1983]], [[/y/1982][1982]], [[/y/1981][1981]], [[/y/1980][1980]], [[/y/1979][1979]], [[/y/1978][1978]], [[/y/1977][1977]], [[/y/1976][1976]], [[/y/1975][1975]], [[/y/1974][1974]], [[/y/1973][1973]], [[/y/1972][1972]], [[/y/1971][1971]], [[/y/1970][1970]], [[/y/1969][1969]], [[/y/1968][1968]], [[/y/1967][1967]], [[/y/1966][1966]], [[/y/1965][1965]], [[/y/1964][1964]], [[/y/1963][1963]], [[/y/1962][1962]], [[/y/1961][1961]], [[/y/1960][1960]], [[/y/1959][1959]], [[/y/1958][1958]], [[/y/1957][1957]].

** Rachete orbitale active

  + SUA: [[/r/falcon9][Falcon 9]], [[/r/falconh][Falcon Heavy]], [[/r/sls][SLS]], [[/r/atlasv][Atlas V]], [[/r/delta4][Delta IV]], [[/r/delta4h][Delta IV Heavy]], [[/r/electron][Electron]], [[/r/fireflya][Firefly Alpha]], [[/r/launcherone][LauncherOne]], [[/r/astrarocket][Astra]], [[/r/antares][Antares]], [[/r/minotaur][Minotaur]], [[/r/pegasus][Pegasus]], [[/r/terran1][Terran 1]], [[/r/rs1][RS1]];
  + China: [[/r/cz2c][CZ-2C]], [[/r/cz2d][CZ-2D]], [[/r/cz2f][CZ-2F]], [[/r/cz3b][CZ-3B]], [[/r/cz3c][CZ-3C]], [[/r/cz4b][CZ-4B]], [[/r/cz4c][CZ-4C]], [[/r/cz11][CZ-11]], [[/r/cz5][CZ-5]], [[/r/cz6][CZ-6]], [[/r/cz7][CZ-7]], [[/r/cz8][CZ-8]], [[/r/kz1a][KZ-1A]], [[/r/kz11][KZ-11]], [[/r/gushenxing1][Gushenxing-1]], [[/r/lijian1][Lijian-1]], [[/r/shuangquxian][Shuang Quxian 1]], [[/r/jielong][Jielong]], [[/r/osm1][OS-M1]], [[/r/zhuque2][Zhuque-2]], [[/r/kt2][KT-2]], [[/r/tianlong2][Tianlong-2]];
  + Rusia: [[/r/soyuz21][Soyuz-2.1]], [[/r/soyuz21v][Soyuz-2.1v]], [[/r/protonm][Proton-M]], [[/r/angara12][Angara-1.2]], [[/r/angaraa5][Angara-A5]];
  + Europa: [[/r/ariane5][Ariane 5]], [[/r/vega][Vega]];
  + Japonia: [[/r/hii][H-II]], [[/r/h3][H3]], [[/r/epsilon][Epsilon]];
  + India: [[/r/sslv][SSLV]], [[/r/pslv][PSLV]], [[/r/gslvmk2][GSLV Mk. 2]], [[/r/lvm3][LVM3]];
  + Iran: [[/r/safir][Safir]], [[/r/simorgh][Simorgh]], [[/r/qased][Qased]];
  + Israel: [[/r/shavit][Shavit]];
  + Coreea de Sud: [[/r/nuri][Nuri]];
  + Coreea de Nord: [[/r/Kwangmyongsong][Kwangmyongsong]], [[/r/cheonlima1][Cheonlima-1]].

* About
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: about
:EXPORT_TITLE: Despre site
:END:

** Despre site
Site-ul parsec.ro este un site cu materiale despre explorarea spațiului, proiect personal care a început în 2009, după o vizită la Centrul Spațial Johnson al NASA, din Houston. Eu sunt Claudiu Tănăselia, fizician, cercetător științific la INCDO INOE2000 ICIA Cluj-Napoca.

În timp, am evoluat de la un blog cu noutăți din domeniul explorării spațiului (activ între 2009 și 2018) la un site care în prezent conține câteva materiale în care sunt concentrate informațiile cu privire la activitățile spațiale curente, articole care vor fi aduse la zi pe măsură ce informațiile prezentate vor necesita acest lucru.

Pentru un flux mai dens de știri, mă puteți urmări pe Facebook, vă puteți abona la newsletter sau puteți asculta podcastul Buletin Cosmic.

** Detalii tehnice
Tabelele cu statistici ale rachetelor și lansărilor orbitale sunt generate din [[https://planet4589.org/space/gcat/][GCAT: General Catalog of Artificial Space Objects]], date folosite cu aprobarea lui [[https://planet4589.org/][Jonathan McDowell]], alterate pentru a le face mai concise și potrivite site-ului de față. Site-ul este generat folosind Emacs (org-mode, Emacs-Lisp și ox-hugo) și afișat cu ajutorul Hugo și GitHub Pages.

** Contact
Apreciez orice feedback, comentariu, sugestie, critică constructivă. Mă găsiți oricând la adresa de mail contact@parsec.ro sau îmi puteți trimite un mesaj pe pagina de [[https://www.facebook.com/claudiu.tanaselia][Facebook]].

* Statistici anuale
:PROPERTIES:
:EXPORT_HUGO_SECTION: y
:END:

** Lansări total
:PROPERTIES:
:EXPORT_FILE_NAME: total
:EXPORT_TITLE: Lansări orbitale
:END:

Din 1957 și până în prezent au avut loc src_emacs-lisp[:results value raw]{grand-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{grand-successes} lansări reușite și src_emacs-lisp[:results value raw]{grand-failures} eșecuri (încărcătura primară nu a ajuns pe orbită).

În tabelul de mai jos sunt prezentate numărul total de lansări orbitale, pentru fiecare stat în parte, începând cu 1957. Câteva precizări: lansările URSS și ale Rusiei nu sunt numărate separat, iar lansările statelor europene, fie prin Arianespace sau separat, sunt catalogate drept lansări europene, indiferent de locul de unde este lansată racheta. În stabilirea țării în a cărei portofoliu intră lansarea, am considerat că statul în care este înregistrat operatorul este cel consiederat în statistici (de exemplu, lansările rachetei Electron din Noua Zeelandă sunt lansări ale Statelor Unite, pentru că Rocket Lab, compania care operează lansatorul, este o companie americană).

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (table-launches-grand-total)
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-by-year-and-country)
#+END_SRC

** Lansări 2023
:PROPERTIES:
:EXPORT_FILE_NAME: 2023
:EXPORT_TITLE: Lansări orbitale 2023
:END:

În anul 2023, au avut loc un total de src_emacs-lisp[:results value raw]{2023-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2023-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2023")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (list-launches-for-year "2023" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

* Lansări pre-2023 :noexport:

#+BEGIN_SRC emacs-lisp
;; Uncomment this (and place it below this code block) _only_ in case of data format change.
;; Old years Markdown files are already generated, there's no reason to generate them
;; every single time, _unless_ there's a data format change.
; #+INCLUDE: "past-years.org"
#+END_SRC

* Rachete
:PROPERTIES:
:EXPORT_HUGO_SECTION: r
:END:

** Falcon 9
:PROPERTIES:
:EXPORT_FILE_NAME: falcon9
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Falcon 9")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Falcon Heavy
:PROPERTIES:
:EXPORT_FILE_NAME: falconh
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Falcon Heavy")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** SLS Block 1
:PROPERTIES:
:EXPORT_FILE_NAME: sls
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "SLS")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Atlas V
:PROPERTIES:
:EXPORT_FILE_NAME: atlasv
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Atlas V")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Delta IV
:PROPERTIES:
:EXPORT_FILE_NAME: delta4
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Delta 4M")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Delta IV Heavy
:PROPERTIES:
:EXPORT_FILE_NAME: delta4h
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Delta 4H")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Electron
:PROPERTIES:
:EXPORT_FILE_NAME: electron
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Electron")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Firefly Alpha
:PROPERTIES:
:EXPORT_FILE_NAME: fireflya
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Firefly Alpha")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** LauncherOne
:PROPERTIES:
:EXPORT_FILE_NAME: launcherone
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "LauncherOne")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Astra Rocket
:PROPERTIES:
:EXPORT_FILE_NAME: astrarocket
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Astra Rocket")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Antares
:PROPERTIES:
:EXPORT_FILE_NAME: antares
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Antares")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Minotaur
:PROPERTIES:
:EXPORT_FILE_NAME: minotaur
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Minotaur")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Pegasus
:PROPERTIES:
:EXPORT_FILE_NAME: pegasus
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Pegasus")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Terran 1
:PROPERTIES:
:EXPORT_FILE_NAME: terran1
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Terran 1")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** RS1
:PROPERTIES:
:EXPORT_FILE_NAME: rs1
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "RS1")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 2C
:PROPERTIES:
:EXPORT_FILE_NAME: cz2c
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 2C")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 2D
:PROPERTIES:
:EXPORT_FILE_NAME: cz2d
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 2D")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 2F
:PROPERTIES:
:EXPORT_FILE_NAME: cz2f
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 2F")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 3B
:PROPERTIES:
:EXPORT_FILE_NAME: cz3b
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 3B")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 3C
:PROPERTIES:
:EXPORT_FILE_NAME: cz3c
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 3C")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 4B
:PROPERTIES:
:EXPORT_FILE_NAME: cz4b
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 4B")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 4C
:PROPERTIES:
:EXPORT_FILE_NAME: cz4c
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 4C")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 11
:PROPERTIES:
:EXPORT_FILE_NAME: cz11
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 11")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 5
:PROPERTIES:
:EXPORT_FILE_NAME: cz5
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 5")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 6
:PROPERTIES:
:EXPORT_FILE_NAME: cz6
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 6")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 7
:PROPERTIES:
:EXPORT_FILE_NAME: cz7
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 7")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Changzheng 8
:PROPERTIES:
:EXPORT_FILE_NAME: cz8
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Changzheng 8")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Kuaizhou-1A
:PROPERTIES:
:EXPORT_FILE_NAME: kz1a
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Kuaizhou-1A")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Kuaizhou-11
:PROPERTIES:
:EXPORT_FILE_NAME: kz11
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Kuaizhou-11")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Gushenxing 1
:PROPERTIES:
:EXPORT_FILE_NAME: gushenxing1
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Gushenxing 1")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Lijian-1
:PROPERTIES:
:EXPORT_FILE_NAME: lijian1
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Lijian-1")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Shuang Quxian
:PROPERTIES:
:EXPORT_FILE_NAME: shuangquxian
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Shuang Quxian")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Jielong
:PROPERTIES:
:EXPORT_FILE_NAME: jielong
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Jielong")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** OS-M1
:PROPERTIES:
:EXPORT_FILE_NAME: osm1
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "OS-M1")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Zhuque-2
:PROPERTIES:
:EXPORT_FILE_NAME: zhuque2
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Zhuque-2")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** KT-2
:PROPERTIES:
:EXPORT_FILE_NAME: kt2
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "KT-2")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Tianlong-2
:PROPERTIES:
:EXPORT_FILE_NAME: tianlong2
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Tianlong")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Soyuz-2.1
:PROPERTIES:
:EXPORT_FILE_NAME: soyuz21
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Soyuz-2.1")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Soyuz-2.1v
:PROPERTIES:
:EXPORT_FILE_NAME: soyuz21v
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Soyuz-2.1v")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Proton-M
:PROPERTIES:
:EXPORT_FILE_NAME: protonm
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Proton-M")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Angara-1.2
:PROPERTIES:
:EXPORT_FILE_NAME: angara12
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Angara-1.2")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Angara-A5
:PROPERTIES:
:EXPORT_FILE_NAME: angaraa5
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Angara A5")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Ariane 5
:PROPERTIES:
:EXPORT_FILE_NAME: ariane5
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Ariane 5")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Vega
:PROPERTIES:
:EXPORT_FILE_NAME: vega
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Vega")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** H-II
:PROPERTIES:
:EXPORT_FILE_NAME: hii
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Vega")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** H3
:PROPERTIES:
:EXPORT_FILE_NAME: h3
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Vega")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Epsilon
:PROPERTIES:
:EXPORT_FILE_NAME: epsilon
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Vega")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** SSLV
:PROPERTIES:
:EXPORT_FILE_NAME: sslv
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "SSLV")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** PSLV
:PROPERTIES:
:EXPORT_FILE_NAME: pslv
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "PSLV")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** GSLV Mk II
:PROPERTIES:
:EXPORT_FILE_NAME: gslvmk2
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "GSLV Mk II")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** LVM3
:PROPERTIES:
:EXPORT_FILE_NAME: lvm3
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "LVM3")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Safir
:PROPERTIES:
:EXPORT_FILE_NAME: safir
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Safir")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Simorgh
:PROPERTIES:
:EXPORT_FILE_NAME: simorgh
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Simorgh")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Qased
:PROPERTIES:
:EXPORT_FILE_NAME: qased
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Qased")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Shavit
:PROPERTIES:
:EXPORT_FILE_NAME: shavit
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Shavit")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Nuri
:PROPERTIES:
:EXPORT_FILE_NAME: nuri
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Nuri")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Kwangmyongsong
:PROPERTIES:
:EXPORT_FILE_NAME: kwangmyongsong
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Kwangmyongsong")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Cheonlima-1
:PROPERTIES:
:EXPORT_FILE_NAME: cheonlima1
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Cheonlima-1")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

* Materiale diverse
:PROPERTIES:
:EXPORT_HUGO_SECTION: m
:END:

** Buran
:PROPERTIES:
:EXPORT_FILE_NAME: buran
:END:

Ne aflăm la mijlocul anilor ’70, în plin război rece și în era post-Apollo. Cursa spațială s-a încheiat deja, dar cursa înarmării continua și bugetele pentru apărare, atât în SUA cât și în URSS sunt practic nelimitate. Încă dinainte de aselenizare, NASA trasase deja un plan pentru dezvoltarea unui vehicul reutilizabil care să permită accesul frecvent și ieftin la orbita terestră joasă, construirea unei navete spațiale devenind preocuparea principală a agenției spațiale americane. Dar nu doar Statele Unite au avut o navetă spațială.

*** Planuri pentru Buran

Planurile americane pentru noul vehicul au fost atât de îndrăznețe încât sovieticii, când au aflat de ele, le-au considerat doar un paravan pentru adevăratul scop al navetei spațiale: misiuni militare extrem de eficiente. Faptul că forțele aeriene s-au implicat serios în proiect, au decis în cele din urmă o mare parte din parametrii navetei spațiale și chiar au construit o rampă de lansare la baza aeriană de la Vandenberg, de unde naveta ar fi putut fi lansată pe o orbită polară, nu au făcut decât să confirme temerile sovietice. De pe o astfel de orbită polară, rușii se temeau că naveta ar fi putut lansa extrem de rapid o încărcătură nucleară deasupra teritoriului sovietic, temere inspirată parțial și din propriile planuri de a trimite, în cazul unui conflict armat, o rachetă intercontinentală pe deasupra polului sud, în locul străbaterii Atlanticului. Este adevărat că, teoretic, naveta spațială putea fi lansată de la baza Vandenberg și se putea întoarce la locul de lansare după efectuarea unei singure orbite, facilitate posibilă datorită aripilor delta, care îi ofereau o largă autonomie de zbor la reintrarea în atmosferă, detaliu cerut cu insistență de forțele aeriene.

În aceste condiții, s-a luat în 1976 decizia de a construi un echivalent sovietic al navetei spațiale. Vehiculul nu avea să aibă alt scop decât acela de a fi similar cu modelul american, pentru ca URSS să aibă la îndemână un instrument de răspuns în cazul în care naveta spațială avea să fie folosită în operațiuni militare.

Astăzi putem spune cu certitudine că nimeni din lanțul ierarhic din SUA nu avea cu adevărat intenția de a bombarda Moscova cu încărcături nucleare plasate în cala navetei spațiale. Forțele aeriene erau însă atrase de proiect deoarece planul ca naveta va înlocui toate celelalte metode de lansare părea unul atractiv, motiv pentru care s-au asigurat că vehiculul va avea cala suficient de mare pentru a găzdui cei mai voluminoși sateliți de spionaj existenți la acea vreme și că, la nevoie, se vor putea efectua lansări pe orbită polară. Însă eficiența navetei spațiale nu avea să fie satisfăcătoare. Aceasta nu s-a apropiat de rata de 50-60 de lansări anuale și astfel nu a devenit niciodată profitabilă economic. Chiar dacă armata a folosit în câteva rânduri naveta pentru încărcături secrete, toate lansările navetei au avut până la urmă loc de la centrul spațial

Kennedy din Florida. Baza de la Vandenberg nu avea să fie folosită niciodată pentru lansări pe orbite polare iar armată nu renunțase la rachete pentru lansările curente. Însă planul sovietic de a construi un corespondent avea să fie pus în aplicare și în 1988, Buran, naveta spațială din est, se afla pe rampa de lansare, gata să înceapă o nouă era în programul spațial sovietic, după eșecul tentativei de aselenizare din anii precedenți.

Planurile inițiale pentru Buran nu cuprindeau însă un vehicul identic cu naveta americană. Inițial, se discuta despre construirea unui vehicul de dimensiuni asemănătoare care să fie plasat deasupra rachetei propulsoare. De asemenea, aripile, care reprezintă un balast în cea mai mare parte a unui zborului, aveau să fie și ele micșorate, reducând astfel considerabil masa ansamblului. Această soluție necesita însă modificări aduse rachetei propulsoare pentru a face față sarcinii suplimentare, lucru ce i-ar fi redus eficiența. Pentru a accelera procesul de producție și pentru a profita deja de cercetarea efectuată de NASA, s-a optat pentru un vehicul de formă similară cu cel american. A mai apărut însă o problemă: dacă motorul avea să fie atașat de vehicul, masa navetei era atât de mare încât nu putea fi transportată pe calea aerului de nici un avion existent la acea dată în URSS. Mai mult, plasarea motoarelor în vehicul însemna că acestea trebuiau să fie refolosibile, o situație cu care inginerii sovietici nu erau deloc confortabili. În cele din urmă s-a optat pentru mutarea motoarelor principale în partea posterioară a rezervorului extern (care astfel devenea o rachetă de sine stătătoare), reducând astfel masa vehiculului cu aproximativ 40 de tone. Motoarele nu mai trebuiau astfel să funcționeze pentru mai mult de o lansare, iar racheta, în această configurație, putea fi folosită și pentru lansări de alte încărcături, nu neapărat pentru Buran, un avantaj pe care NASA nu îl avea. Pentru a compensa deplasare centrului de masă prin îndepărtarea motorului, aripile, identice ca formă și suprafață cu cele ale navetei spațiale, au fost plasate mai aproape de cabină.

Exista la un moment dat un plan de a monta pe aripa posterioară a navetei două motoare cu reacție. Ar fi fost o diferență majoră față de navetele americane deoarece aceste motoare nu ar fi permis doar o mai bună manevrabilitate înainte de aterizare (Buran nu ar mai fi fost astfel doar un planor imens care cădea spre pista de lansare, ci un avion controlabil) dar și posibilitatea ca naveta să poată decola singură pentru zboruri atmosferice, eliminând astfel montarea ei pe un alt avion pentru transferul între diversele centre de testare din URSS. Însă această modificare nu a mai avut loc. Motivele sunt diverse: se pare că motoarele nu ar fi fost finalizate pentru zborul inaugural al lui Buran din 1988. Iar montarea lor ar fi dat mai multe bătăi de cap inginerilor: centrul de greutate avea să se modifice, masa navetei ar fi crescut (pe lângă motoare era nevoie de sisteme de protecție a acestora și un rezervor cu combustibil), profilul aerodinamic era altul (inclusiv un stres suplimentar pe coada navetei), aspecte ce necesitau teste suplimentare în tunelul aerodinamic, iar toate aceste inconveniente ar fi amânat și mai mult primul zbor al lui Buran.

Cinci vehicule trebuiau să fie operaționale în programul Buran. Denumirile lor însă nu au fost niciodată foarte clar stabilite. Dacă vehiculul care a zburat în spațiu este denumit astăzi Buran (după programul cu același nume, care în românește se traduce prin viscol), când a ajuns la Baikonur, pe fuselaj stătea scris Baikal. Ulterior, numele a fost modificat în Buran, deși în primele imagini apărute în presa sovietică, numele nu era vizibil, fiind înlăturat prin postprocesare. Ce se cunoaște însă cu siguranță este indicativul: 1K. Al doilea vehicul avea să fie 2K și așa mai departe. Folosind această notație, prima misiune ar fi fost codificată 1K1, deoarece era primul zbor al primului vehicul, a doua 2K1, deoarece planul era să fie folosit al doilea vehicul pentru a doua lansare din programul Buran etc. Numele celei de-a doua navete nu a fost niciodată stabilit oficial. Deși în presa vestică apărea Ptichka (păsărică), această variantă nu este sprijinită de nici o sursă sovietică, Ptichka fiind mai degrabă un diminutiv aplicat de ruși tuturor navetelor, nu uneia singure. Burya (furtună) ar fi putut însă fi folosit al doilea vehicul operațional, derivând tot dintr-un element violent al naturii, iar Uragan pentru a treia, dar având în vedere că nici un alt vehicul nu a mai fost lansat după Buran, numele acestora nu a fost niciodată clar stabilit.

*** Activități orbitale

Ajunsă pe orbită, Buran își putea controla orientarea folosind un sistem de propulsoare similar cu cel al navetei spațiale (38 la număr, astfel plasate încât să poată oferi navetei libertate deplină în jurul centrului de masă), însă inginerii sovietici au optat pentru folosirea unui combustibil diferit, aceasta fiind, după plasarea motoarelor, una din cele mai mari diferențe dintre cele două vehicule. Navetele americane, la fel ca toate vehiculele orbitale dinaintea lor, foloseau pentru orientarea vehiculului un tip combustibil format din două substanțe (tetraoxid de azot și dimetilhidrazină) care se aprindea spontan la contactul dintre ele, fără să mai fie nevoie de oxidant sau alte sisteme de aprindere complexe. Un alt avantaj era faptul că puteau fi păstrate o perioadă îndelungată, fără a cauza probleme suplimentare. Însă, pentru Buran s-a optat pentru folosirea unui combustibil pe bază de oxigen lichid și hidrocarburi sintetice, denumit sintin. Acest lucru prezenta câteva avantaje: performanțele motoarelor de poziționare erau mai bune, combustibilul putea fi manevrat mai ușor la sol din cauza unei toxicități mult mai reduse iar oxigenul lichid putea fi pompat, la nevoie, și direct în pilele de combustie, asigurând astfel un nivel suplimentar de redundanță al acestora. Dezavantajul sistemului sovietic a fost însă o masă mai mare (fiind cu o tonă mai greu decât corespondentul american), avea nevoie și de un sistem suplimentar de aprindere și necesita protecție termică suplimentară pentru a menține oxigenul în stare lichidă pe toată durata zborului.

Cele două propulsoare plasate în partea posterioară a navetei (denumite MOS) erau folosite pentru manevre de revenire în atmosferă sau pentru corecție orbitală. Spre deosebire însă de varianta americană (OMS), doar unul era necesar pentru execuția unei manevre, folosirea simultană fiind rezervată doar situațiilor de urgență.

*** Energia

Propulsia avea să fie asigurată de o rachetă nouă, construită special pentru acest scop, denumită Energia. Propulsată de patru motoare centrale RD-0120 cu combustibil lichid (hidrogen și oxigen) și patru boostere suplimentare, fiecare cu câte patru motoare RD-170 ce ardeau cherosen și oxigen, Energia putea transporta până la 100 de tone pe orbita terestră joasă și 20 de tone pe orbită geostaționară. Avea să fie cea mai complexă rachetă construită vreodată de URSS. Spre deosebire de sistemul de propulsie american al navetei, Energia era proiectată să transporte și alte încărcături, așa că aceasta avea propriul sistem de navigație, independent de computerele de la bordul Buran și putea fi folosită independent de aceasta. Computerul central se afla în rezervorul principal iar fiecare din cele patru boostere avea propriul computer de zbor, conectat însă în permanență cu cel central. Pentru a nu repeta catastrofalele lansări ale rachetei N-1 (care a pus capăt ambițiilor sovietice de a pune un echipaj pe Lună), noua rachetă era dotată cu senzori care detectau scurgeri de gaze și în cazul unui incendiu, se activau sisteme de stingere pe bază de freon. Înainte de lansare, motoarele erau purjate cu azot iar excesul de hidrogen era eliminat, pentru a evita o acumulare și o aprindere accidentală a acestuia, însă spre deosebire de sistemul folosit de NASA, în cazul Energia, surplusul de hidrogen era îndepărtat înainte ca acesta să ajungă la motoare. Un alt sistem de senzori de presiune, temperatură și alți parametri monitoriza permanent motoarele și în cazul unei anomalii îl închideau imediat, înainte de o evoluție catastrofală a acestuia, iar motorul diametral opus putea compensa, dacă era cazul, pentru a nu rata complet misiunea.

*** Primul zbor

În concordanță cu istoria programelor spațiale sovietice și de frica unui nou eșec (cele patru lansări succesive ratate ale rachetei N-1 erau încă proaspete în mințile inginerilor), s-a optat pentru un prim zbor complet automat al lui Buran, fără un echipaj uman. Zborul, prevăzut inițial pentru a dura câteva zile, a fost redus la două orbite. Astfel la bordul Buran nu au fost montate toate subsistemele care aveau să fie prezente în versiunea finală, testul dorea doar să confirme că vehiculul poate decola și poate reveni autonom la sol, după o scurtă incursiune în spațiu. Navetele spațiale americane, deși aveau planificate un sistem automat de zbor, acesta nu avea să fie pus niciodată în funcțiune. Încă din programul Mercury, astronauții americani au cerut un control manual cât mai pronunțat al aparatelor de zbor, ei refuzând să fie doar actori în niște vehicule controlate autonom sau de la sol. Din acest motiv, primul zbor al navetei Columbia a fost unul cu echipaj uman, chiar dacă riscurile erau imense: nimeni nu știa exact cum avea să se comporte naveta spațială în primul său zbor.

Un sistem independent de patru computere denumite Biser-4 (spre deosebire de navetele americane care erau echipate cu patru computere redundante și un al cincilea, de rezervă) avea să fie folosit pentru controlul subsistemelor navetei. Fiind vorba de un vehicul autonom, software-ul de zbor avea să fie de o complexitate ridicată și inginerii îl îmbunătățeau constant de-a lungul testelor, Buran în momentul lansării, folosind a 21-a versiune a acestuia.

În afară de aceste diferențe (motorul plasat pe rezervor, folosirea propulsoarelor cu combustibil lichid și un mai mare grad de automatizare), Buran era foarte asemănătoare cu naveta spațială americană. Oficialii sovietici au pus pe seama legilor aerodinamicii forma identică a fuselajului și a aripilor, însă acestea nu au fost alese de NASA din constrângeri aerodinamice, ci pentru că trebuiau să satisfacă punctual cerințele armatei. Pentru URSS, era mai eficient să folosească deja o formă funcțională și testată, decât să investească resurse într-un concept nou, mai ales că erau cu patru ani ani în urma Statelor Unite în ceea ce privește startul oficial pentru dezvoltarea navetei. Totuși, chiar dacă au avut acces la literatură de specialitate și la parametrii navetei spațiale, inginerii au trebuit să găsească resursele necesare construirii efective a navetei, lucru care nu a fost deloc simplu, având în vedere complexitatea proiectului, așa că meritele URSS în această privință nu trebuie scăzute prea mult pentru faptul că au copiat un model funcțional.

Patru locomotive diesel au fost necesare pentru a deplasa platforma cu naveta și propulsoarele spre rampa de lansare, în 10 octombrie 1988. Lansarea, prevăzută inițial pentru 29 octombrie, avea să fie amânată din cauza unei platforme care, în timpul numărătorii inverse, nu s-a depărtat corespunzător de navetă. Unele probleme ale sistemului de aterizare au fost remediate cu doar o zi înainte. În 15 noiembrie 1988, vremea de la Baikonur ar fi încălcat toate condițiile impuse unei lansări a unei navete americane: temperaturi scăzute, vânt puternic, plafon de nori și precipitații (rușii considerau că un strat de gheață de 2 mm format pe rachetă este acceptabil, în condițiile în care accidentul care a dus la dezintegrarea navetei Challenger tocmai din cauza temperaturilor joase, a avut loc doar cu 2 ani în urmă). Cu toate acestea, la T-10 minute, controlul vehiculului a revenit computerelor de bord. La T-9.9 secunde, cele patru motoare RD-0120 ale rachetei Energia s-au trezit la viață, iar boosterele au fost activate la T-3.7 secunde. A fost exact ora 6:00 la Moscova când Buran, prima și singura navetă spațială sovietică avea să se ridice de pe rampa de lansare și să plonjeze direct în nori, spre dezamăgirea publicului prezent la fața locului. Fotografii au avut la dispoziție doar câteva secunde pentru a surprinde istoricul moment.

Buran era teoretic prevăzută cu două brațe robotice pentru manipularea încărcăturii din cală, spre deosebire de navetele americane care aveau un singur braț. Echipajul putea comanda cele două brațe, dar ele puteau fi comandate și de la sol. Pentru că navetele spațiale americane nu erau prevăzute să zboare fără echipaj uman, cea de-a doua facilitate nu avea să fie niciodată implementată. Nici în primul zbor al lui Buran, naveta nu a fost echipată cu cele două brațe robotice, deoarece în scurta sa excursie orbitală ușile calei nu aveau să fie deschise. Lipseau astfel și radiatoarele necesare pentru evacuarea căldurii excesive (montate în interiorul ușilor calei și expuse doar când acestea erau deschise) iar pilele de combustie nu puteau susține naveta mai mult de 24 de ore. Din aceste motive, dacă Buran nu ar fi reușit să se întoarcă în 15 noiembrie, misiunea ar fi devenit un eșec, prin pierderea vehiculului.

Operațiunile orbitale minimale au decurs fără incidente și după patru ore de zbor, Buran se afla pe pista de aterizare, cu doar o secundă mai devreme decât se planificase inițial. Zborul fusese un succes, dar din păcate, avea să fie pentru ultima dată când un vehicul din programul Buran avea să zboare spre orbită.

*** Epilog

Colapsul Uniunii Sovietice a însemnat sfârșitul programului Buran. Fondurile erau tot mai puține și tot mai mulți se întrebau care mai este necesitatea acestui vehicul, militând pentru cheltuirea sumelor de bani în alte scopuri: stația spațială MIR, iar apoi ISS. Sfârșitul Războiului Rece a însemnat și dispariția scopului primar pentru care Buran fusese construită. Noua Federație Rusă nu mai vedea un inamic în Statele Unite când venea vorba de activități spațiale, iar cele două superputeri au ales, înțelept am putea spune, să colaboreze în loc să se teamă unii de alții. Stația Spațială internațională de astăzi este rezultatul acestei fructoase colaborări.

Programul Buran nu a fost suspendat niciodată oficial. Nu a existat un decret guvernamental care să marcheze finalul său, dar cei direct implicați au început să sesizeze schimbările. Piloții care se antrenau pentru Buran aveau să fie transferați spre alte programe iar celelalte resurse au fost redirecționate spre alte sectoare ale industriei spațiale rusești.

Ce s-a întâmplat însă cu vehiculele deja construite? Povestea lor este una tristă. Buran OK-1.01, naveta care a zburat în spațiu, a fost depozitată la Baikonur, în Kazahstan, într-un hangar, împreună cu o replică a rachetei care a purtat-o pe orbită. În 2002 însă, acoperișul hangarului s-a prăbușit, în timpul unor operațiuni de renovare. Opt oameni și-au pierdut atunci viața, iar naveta a fost distrusă în totalitate. Au mai fost construite, în cadrul programului cu acelși nume, și alte vehicule, unele pentru teste atmosferice iar altele pentru a zbura în spațiu în anii următori zborului test. Acestea, aflate în diverse etape ale asamblării, sunt împrăștiate astăzi prin diverse locuri din lume și se află în stări de conservare mau mult sau mai puțin adecvate. La Baikonur se află și OK-1.02, al doilea vehicul care urma să zboare în spațiu și care în momentul anulării programului, era finalizată în proporție de peste 90%. Aceasta a fost depozitată într-un hangar și în 2021, vandalizată cu grafitti de persoane neidentificate. În Moscova, în Parcul Gorki, a putut fi admirat un vehicul complet (OK-TVA), care a fost folosit pentru teste aerodinamice și care în 2014 a fost mutat în cadrul expoziției permanente VDNKh. Un altul se află în Kazahstan, la intrarea în cosmodromul de la Baikonur. Un alt vehicul care urma să fie simbolul măreției sovietice, a fost expus o perioadă la Sydney cu ocazia Jocurilor Olimpice de vară din 2000, a ajuns la un muzeu din Germania; acesta a fost folosită pentru teste aerodinamice, din acest punct de vedere fiind vehiculul echivalent cu naveta americană Enterprise.

| Indicativ         | Amplasare               | Detalii                           |
|-------------------+-------------------------+-----------------------------------|
| OK-TVA            | Muzeul VDNKh, Moscova   | Folosit pentru teste la sol       |
| OK-TVI            | NIIKhim, Moscova        | Doar secțiunea mediană            |
| OK-M/ML-1         | Intrarea la Baikonur    | Folosit pentru teste la sol       |
| OK-KS             | Centrul Sirius, Sochi   | Folosit pentru teste la sol       |
| OK-M/ML-2         | Baikonur, clădirea 112A | Folosit pentru teste la sol       |
| OK-GLI            | Museul Speyer, Germania | Folosit pentru teste aerodinamice |
| OK-1.01 "Buran"   | Baikonur, clădirea 112  | Vehicul orbital; distrusă în 2002 |
| OK-1.02 "Pitchka" | Baikonur, clădirea 112  | Finalizat 90%                     |
| OK-2.01 "Baikal"  | Baza aeriană Zhukovsky  | Finalizat 50%                     |
| OK-2.02           | Fabrica din Tushino     | Finalizat 20%                     |
| OK-2.03           | Fabrica din Tushino     | Finaliza <20%                     |

Moștenirea programului Buran însă continuă și astăzi. Boosterele rachetei Energia au fost sursă de inspirație pentru rachetele folosite în prezent de către compania Sea Launch iar viitoarea generație de rachete rusești Angara tot de acolo se inspiră. Sistemul de andocare proiectat pentru Buran a fost folosit pentru stația spațială MIR și continuă să fie folosit și astăzi la bordul ISS.

/Articol publicat inițial în revista Știință&Tehnică, iulie 2013/ /și adus la zi ulterior/.

** Meteoriți
:PROPERTIES:
:EXPORT_FILE_NAME: meteoriti 
:END:

În fiecare zi, aproximativ 100 de tone de material cosmic ajung în atmosfera Pământului, dar fiind vorba în principal de particule reduse ca mărime, acestea ard în urma interacțiunii cu atmosfera și nu mai ajung la sol. Aceștia sunt /meteorii/ sau /stelele căzătoare/ care uneori pot fi observate într-o noapte senină pe boltă. Abia dacă materialul extraatmosferic supraviețuiește trecerii prin atmosferă (având o masă inițială suficient de mare pentru a nu fi consumat în întregime de interacțiunea cu aceasta) și ajunge pe suprafața Pământului (sub formă de unul sau mai multe fragmente) putem vorbi de un /meteorit/. Însă având în vedere că suprafața locuită a planetei este totuși destul de redusă, mulți dintre meteoriți ajung în zone nelocuite sau, și mai probabil, în ocean. În medie, zilnic ajung pe Pământ aproximativ doi meteoriți, suficient de mari încât să supraviețuiască trecerii prin atmosferă, însă recuperarea loc din oceane este practic imposibilă, iar dacă aceștia ajung la sol în zone nelocuite și sunt înconjurați de vegetație, identificarea lor este extrem de dificilă (deși nu imposibilă).

*** Denumire
Dacă este vorba despre o zonă populată, meteoritul este denumit după cea mai apropiată așezare umană dotată cu oficiu poștal. Iar numele meteoritului rămâne neschimbat, chiar dacă respectiva așezare (sat, comună sau oraș) își schimbă între timp numele, pentru a nu crea ulterior confuzii printre specialiști. Acesta este motivul pentru care cel mai cunoscut meteorit românesc se numește Mocs, chiar dacă localitatea este denumită astăzi Mociu: în 1882, satul respectiv se numea Mocs. Uneori meteoriți sunt găsiți în zone nelocuite, cum ar fi Sahara sau Antarctica. Ba chiar se organizează expediții în aceste locuri, pentru că este foarte ușor de identificat un meteorit într-o zonă lipsită de vegetație, cum sunt dunele sahariene (care în mișcarea lor pot dezgropa meteoriți îngropați acum câteva secole sau milenii) sau ghețurile din Antarctica, unde topirea zăpezii poate scoate la suprafață meteoriți ajunși pe Pământ acum milioane de ani. Cei găsiți în Sahara primesc prefixul NWA și un număr (North Western African) iar majoritatea celor găsiți în Antarctica sunt găsiți în zona dealurilor Allan Hills, așa că meteoriții recuperați de acolo primesc prefixul ALH și, din nou, un număr.

*** Clasificare
În linii mari, există patru tipuri de meteoriți: condrite, acondrite, fieroși și pietros-fieroși. Condritele arată la exterior, la o primă vedere, ca pietrele de pe Pământ, dar sunt mai dense și mai bogate în fier și nichel. De fapt acesta este un prim test pentru ca o rocă suspectă să provină de dincolo de atmosfera Pământului: dacă este atrasă de un magnet, deci dacă are un conținut ridicat de fier, sunt șanse să avem de-a face cu un meteorit. Desigur, sunt și alte analize: prezența unei cruste (formată la trecerea prin atmosferă), prezența altor elemente care nu se regăsesc în aceleași concentrații în rocile terestre (de exemplu, iridiu) sau prezența unor formațiuni specifice, observate în secțiune cu ochiul liber, formațiuni denumite condrule, ce conțin material cosmic de dinaintea formării sistemului solar. Unii meteoriți sunt însă formați din fier (îi denumim fieroși), iar alții conțin și fier, dar și diverse minerale (pietros-fieroși). Ttoți ceilalți meteoriți care nu pot fi incluși în celelalte categorii sunt denumiți acondrite.

The Meteoritical Society este organizația internațională care inventariază toți acești meteoriți identificați și, dintr-un total de peste 57,000 de meteoriți, aproape 50,000 sunt condrite (peste 86%). Peste 99% dintre meteoriții catalogați provin din centura de asteroizi aflată între Marte și Jupiter. Nu este vorba despre rămășițele unei planete distruse în trecut printr-un impact cosmic, ci de materie planetară care nu a avut o masă suficient de mare pentru a se aglutina într-o planetă, în perioada formării sistemului nostru solar așa cum îl cunoaștem astăzi. Iar, ca o notă, trebuie spus că centura de asteroizi nu are nici pe departe aspectul din filmele SF, densitatea de asteroizi este atât de mică încât NASA nu ia în calcul traiectoriile acestora când trimite câte o sondă dincolo de Marte.

Revenind la meteoriți, există două sub-clase de acondrite care sunt extrem de interesante: meteoriții lunari și meteoriții marțieni. Extrem de rar, se poate întâmpla ca un meteorit obișnuit să lovească suprafața Lunii cu o forță atât de mare încât să desprindă fragmente din crusta acesteia, fragmente care în cele din urmă ajung pe Pământ (să ne aducem aminte că Luna are atmosferă neglijabilă și se află pe orbita Pământului). Din colecția de meteoriți pe care o aveam în întreaga lume, s-au putut ușor identifica cei lunari pentru că a fost comparată compoziția rocilor de pe Lună aduse de misiunile Apollo cu cei câțiva meteoriți care nu prea intrau în clasele deja cunoscute. În prezent se cunosc doar 326 de meteoriți lunari. Similar avem și meteoriți marțieni, doar că probabilitatea ca bucăți de pe Marte să ajungă pe Pământ este destul de mică și poate dura milioane de ani, până când dansul gravitațional al Pământului și al lui Marte în jurul Soarelui pune planeta noastră în drumul prafului marțian, ridicat pe orbită de un impact cu un meteorit clasic (avem inventariați doar 201 meteoriți marțieni). Compoziția izotopică a gazelor din acești meteoriți este similară cu rocile marțiene investigate de roboții Sojourner, Spirit, Opportunity și Curiosity care au ajuns pe suprafața marțiană. 

Avem pe Pământ și meteoriți de pe alte corpuri din sistemul solar? Puțin probabil, din două motive simple: gravitația și atmosfera. Sateliții altor planete se află în câmpul gravitațional al acestora și eventualii meteoriți formați de un impact nu vor ajunge altundeva decât pe planeta respectivă. Mercur se află prea aproape de Soare ca un impact să disloce un fragment care să-și facă drum spre Pământ (deși acum câțiva ani exista un zvon că ar fi fost descoperit un meteorit mercurian, însă majoritatea specialiștilor în domeniu au căzut de acord că acest lucru nu este posibil). Venus are o atmosferă mult prea densă pentru a putea permite eventualelor fragmente să o părăsească, iar dincolo de Marte nu mai avem planete telurice, care să poate genera meteoriți.

*** Meteoriți românești
Motivul pentru care majoritatea meteoriților par să cadă în Rusia este faptul că Rusia este statul cu cea mai mare suprafață, deci cu cele mai mare șanse ca meteoriții să o nimerească (la care se mai adaugă și faptul ca în Rusia foarte mulți șoferi dispun de camere video). 

Din fericire țara noastră nu are o suprafață chiar mică, ceea ce înseamnă că există șanse să găsim meteoriți și în interiorul granițelor noastre (comparativ cu majoritatea vecinilor noștri). The Meteoritical Society inventariază 9 meteoriți, deși de fapt sunt 10 (meteoritul Zsadany a fost recuperat din apropierea graniței cu Ungaria și în prezent ambele state îl revendică).

Din păcate, toți cei 9 sau 10 meteoriți românești sunt condrite, adică cei mai comuni meteoriți. Doi dintre ei (Gresia și Tuzla) au fost descoperiți întâmplător (în 1990 și respectiv 1920), dar restul au avut parte de martori când au străbătut atmosfera (în limbaj de specialitate, despre primii se spune că sunt /finds/, iar cei care sunt observați înainte de a ajunge pe Pământul sunt /falls/). Pe lângă Mocs (astăzi Mociu) și Zsadany, de care am pomenit deja, am mai avut parte de meteoriți la Kakowa (1858), Mezö-Madaras (1852), Ohaba (1857), Sopot (1927), Tauți (1937) și cel mai recent, Pleșcoi (2008).

În tabelul următor sunt listați toți meteoriți românești identificați până în prezent, conform bazei de date oficiale[fn:met1], plus corecțiile ulterioare[fn:met2].

| Nr. | Nume         |   An | Localitate      | Coordonate       | Tip  | Masă     | Obs. |
|-----+--------------+------+-----------------+------------------+------+----------+------|
|   1 | Mezö-Madaras | 1852 | Mădăraș, MS     | 46˚36'N, 24˚26'E | L3.7 | 22.70 kg | /fall/ |
|   2 | Ohaba        | 1857 | Ohaba, AB       | 46˚04'N, 23˚47'E | H5   | 16.25 kg | /fall/ |
|   3 | Kakowa       | 1858 | Grădinari, CS   | 45°08'N, 21°40'E | L6   | 577 g    | /fall/ |
|   4 | Mocs         | 1882 | Mociu, CJ       | 46°48'N, 24°02'E | L5-6 | 300 kg   | /fall/ |
|   5 | Zsadany      | 1875 | Cornești, TM    | 45°55'N, 21°13'E | H5   | 552 g    | /fall/ |
|   6 | Tuzla        | 1920 | Tuzla, CT       | 44°01'N, 28°38'E | L6   | 236 g    | /find/ |
|   7 | Sopot        | 1927 | Sopot, DJ       | 44°25'N, 23°30'E | OC   | 958 g    | /fall/ |
|   8 | Tauti        | 1937 | Tauti, AR       | 46°43'N, 23°30'E | L6   | 21 kg    | /fall/ |
|   9 | Gresia       | 1990 | Gresia, TR      | 44°10'N, 24°55'E | H4   | 26.9 kg  | /find/ |
|  10 | Pleșcoi      | 2008 | Pleșcoi, BZ     | 45°16'N, 26°42'E | L5-6 | 6.91 kg  | /fall/ |
|-----+--------------+------+-----------------+------------------+------+----------+------|


[fn:met1] [[https://www.lpi.usra.edu/meteor/metbull.php?sea=&sfor=names&ants=&nwas=&falls=&valids=&stype=contains&lrec=50&map=ge&browse=&country=Romania&srt=name&categ=All&mblist=All&rect=&phot=&strewn=&snew=0&pnt=Normal%20table&dr=&page=0][Meteoritical Bulletin Database, Romanian Meteorites]]
[fn:met2] [[https://scholarcommons.usf.edu/geologia/vol58/iss2/art5/][Luttge-Pop D., Andrei R., Har N., Historical Romanian meteorites: emendations of official catalogue records, Studia UBB Geologia 58 (2): 41-45, 2013 ]]

* Footer :noexport:

#+BEGIN_SRC: emacs-lisp
;; This part should be left at the end of the document.
;; Old Bulletins are already exported as Markdown files,
;; so it makes little sense to export them every single time
;; (it will just make the export time longer without a real gain).
;; Uncomment this if you REALLY want to re-export old Bulletins.
; #+INCLUDE: "old-buls.org"
#+END_SRC
