#+AUTHOR: Claudiu
#+HUGO_BASE_DIR: ../
#+LANGUAGE: ro

#+BEGIN_SRC emacs-lisp :eval yes :results silent
  (load-file "func.el")
  (set-yearly-totals)
#+END_SRC

* Index
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: _index
:EXPORT_TITLE: știri din spațiu
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :fractions false
:END:

** Rachete, astronauți și sonde interplanetare
Siteul de față reprezintă o colecție personală de materiale, articole și notițe (mai mult sau mai puțin structurate) despre explorarea spațiului cosmic, adusă frecvent la zi și mereu extinsă, cu un accent pe rachete și lansări orbitale.

Știrile sunt grupate în Buletine Cosmice, distribuit sub formă de [[https://buletin.parsec.ro/][newsletter]] sau [[https://buletin.parsec.ro/notes][blog]].

** Cele mai recente lansări orbitale

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-last-10 gcatdata 0 2 3 5 6 8 12 13)
#+END_SRC

** Lansări orbitale

+ Lansări orbitale din [[/y/2023][anul curent]];
+ [[/y/total][Statistici generale]];
+ Statistici anuale: [[/y/2022][2022]], [[/y/2021][2021]], [[/y/2020][2020]], [[/y/2019][2019]], [[/y/2018][2018]], [[/y/2017][2017]], [[/y/2016][2016]], [[/y/2015][2015]], [[/y/2014][2014]], [[/y/2013][2013]], [[/y/2012][2012]], [[/y/2011][2011]], [[/y/2010][2010]], [[/y/2009][2009]], [[/y/2008][2008]], [[/y/2007][2007]], [[/y/2006][2006]], [[/y/2005][2005]], [[/y/2004][2004]], [[/y/2003][2003]], [[/y/2002][2002]], [[/y/2001][2001]], [[/y/2000][2000]], [[/y/1999][1999]], [[/y/1998][1998]], [[/y/1997][1997]], [[/y/1996][1996]], [[/y/1995][1995]], [[/y/1994][1994]], [[/y/1993][1993]], [[/y/1992][1992]], [[/y/1991][1991]], [[/y/1990][1990]], [[/y/1989][1989]], [[/y/1988][1988]], [[/y/1987][1987]], [[/y/1986][1986]], [[/y/1985][1985]], [[/y/1984][1984]], [[/y/1983][1983]], [[/y/1982][1982]], [[/y/1981][1981]], [[/y/1980][1980]], [[/y/1979][1979]], [[/y/1978][1978]], [[/y/1977][1977]], [[/y/1976][1976]], [[/y/1975][1975]], [[/y/1974][1974]], [[/y/1973][1973]], [[/y/1972][1972]], [[/y/1971][1971]], [[/y/1970][1970]], [[/y/1969][1969]], [[/y/1968][1968]], [[/y/1967][1967]], [[/y/1966][1966]], [[/y/1965][1965]], [[/y/1964][1964]], [[/y/1963][1963]], [[/y/1962][1962]], [[/y/1961][1961]], [[/y/1960][1960]], [[/y/1959][1959]], [[/y/1958][1958]], [[/y/1957][1957]].

** Rachete orbitale active

  + SUA: [[/r/falcon9][Falcon 9]], [[/r/falconh][Falcon Heavy]], [[/r/sls][SLS]], [[/r/atlasv][Atlas V]], [[/r/delta4][Delta IV]], [[/r/delta4h][Delta IV Heavy]], [[/r/electron][Electron]], [[/r/fireflya][Firefly Alpha]], [[/r/launcherone][LauncherOne]], [[/r/astrarocket][Astra]], [[/r/antares][Antares]], [[/r/minotaur][Minotaur]], [[/r/pegasus][Pegasus]], [[/r/terran1][Terran 1]], [[/r/rs1][RS1]];
  + China: CZ-2C, CZ-2D, CZ-2F, CZ-3B, CZ-3C, CZ-4B, CZ-4C, CZ-11, CZ-5, CZ-6, CZ-7, CZ-8, KZ-1A, KZ-11, Gushenxing-1, Lijian-1, Shuang Quxian 1, Jielong-1, OS-M1, Zhuque-2, KT-2, Tianlong-2;
  + Rusia: Soyuz-2.1, Soyuz-2.1v, Angara-1.2, Proton-M, Angara-A5;
  + Europa: Ariane 5, Vega-C;
  + Japonia: H-II, H3, Epsilon;
  + India: SSLV, PSLV, GSLV Mk. 2, LVM3;
  + Iran: Safir, Simorgh, Qased;
  + Israel: Shavit;
  + Coreea de Sud: Nuri;
  + Coreea de Nord: Kwangmyongsong, Cheonlima-1.
  
* About
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: about
:EXPORT_TITLE: Despre site
:END:

** Despre site
Site-ul parsec.ro este un site cu materiale despre explorarea spațiului, proiect personal care a început în 2009, după o vizită la Centrul Spațial Johnson al NASA, din Houston. Eu sunt Claudiu Tănăselia, fizician, cercetător științific la INCDO INOE2000 ICIA Cluj-Napoca.

În timp, am evoluat de la un blog cu noutăți din domeniul explorării spațiului (activ între 2009 și 2018) la un site care în prezent conține câteva materiale în care sunt concentrate informațiile cu privire la activitățile spațiale curente, articole care vor fi aduse la zi pe măsură ce informațiile prezentate vor necesita acest lucru.

Pentru un flux mai dens de știri, mă puteți urmări pe Facebook, vă puteți abona la newsletter sau puteți asculta podcastul Buletin Cosmic.

** Detalii tehnice
Tabelele cu statistici ale rachetelor și lansărilor orbitale sunt generate din [[https://planet4589.org/space/gcat/][GCAT: General Catalog of Artificial Space Objects]], date folosite cu aprobarea lui [[https://planet4589.org/][Jonathan McDowell]], alterate pentru a le face mai concise și potrivite site-ului de față. Site-ul este generat folosind Emacs (org-mode, Emacs-Lisp și ox-hugo) și afișat cu ajutorul Hugo și GitHub Pages.

** Contact
Apreciez orice feedback, comentariu, sugestie, critică constructivă. Mă găsiți oricând la adresa de mail contact@parsec.ro sau îmi puteți trimite un mesaj pe pagina de [[https://www.facebook.com/claudiu.tanaselia][Facebook]].

* Statistici anuale
:PROPERTIES:
:EXPORT_HUGO_SECTION: y
:END:

** Lansări total
:PROPERTIES:
:EXPORT_FILE_NAME: total
:EXPORT_TITLE: Lansări orbitale
:END:

Din 1957 și până în prezent au avut loc src_emacs-lisp[:results value raw]{grand-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{grand-successes} lansări reușite și src_emacs-lisp[:results value raw]{grand-failures} eșecuri (încărcătura primară nu a ajuns pe orbită).

În tabelul de mai jos sunt prezentate numărul total de lansări orbitale, pentru fiecare stat în parte, începând cu 1957. Câteva precizări: lansările URSS și ale Rusiei nu sunt numărate separat, iar lansările statelor europene, fie prin Arianespace sau separat, sunt catalogate drept lansări europene, indiferent de locul de unde este lansată racheta. În stabilirea țării în a cărei portofoliu intră lansarea, am considerat că statul în care este înregistrat operatorul este cel consiederat în statistici (de exemplu, lansările rachetei Electron din Noua Zeelandă sunt lansări ale Statelor Unite, pentru că Rocket Lab, compania care operează lansatorul, este o companie americană).

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (table-launches-grand-total)
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-by-year-and-country)
#+END_SRC

** Lansări 2023
:PROPERTIES:
:EXPORT_FILE_NAME: 2023
:EXPORT_TITLE: Lansări orbitale 2023
:END:

În anul 2023, au avut loc un total de src_emacs-lisp[:results value raw]{2023-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2023-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2023")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (list-launches-for-year "2023" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))

;; Uncomment this (and place it below this code block) _only_ in case of data format change.
;; Old years Markdown files are already generated, there's no reason to generate them
;; every single time, _unless_ there's a data format change.
; #+INCLUDE: "past-years.org"
#+END_SRC

* Rachete
:PROPERTIES:
:EXPORT_HUGO_SECTION: r
:END:

** Falcon 9
:PROPERTIES:
:EXPORT_FILE_NAME: falcon9
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Falcon 9")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Falcon Heavy
:PROPERTIES:
:EXPORT_FILE_NAME: falconh
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Falcon Heavy")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** SLS Block 1
:PROPERTIES:
:EXPORT_FILE_NAME: sls
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "SLS")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Atlas V
:PROPERTIES:
:EXPORT_FILE_NAME: atlasv
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Atlas V")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Delta IV
:PROPERTIES:
:EXPORT_FILE_NAME: delta4
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Delta 4M")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Delta IV Heavy
:PROPERTIES:
:EXPORT_FILE_NAME: delta4h
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Delta 4H")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Electron
:PROPERTIES:
:EXPORT_FILE_NAME: electron
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Electron")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Firefly Alpha
:PROPERTIES:
:EXPORT_FILE_NAME: fireflya
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Firefly Alpha")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** LauncherOne
:PROPERTIES:
:EXPORT_FILE_NAME: launcherone
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "LauncherOne")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Astra Rocket
:PROPERTIES:
:EXPORT_FILE_NAME: astrarocket
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Astra Rocket")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Antares
:PROPERTIES:
:EXPORT_FILE_NAME: antares
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Antares")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Minotaur
:PROPERTIES:
:EXPORT_FILE_NAME: minotaur
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Minotaur")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Pegasus
:PROPERTIES:
:EXPORT_FILE_NAME: pegasus
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Pegasus")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** Terran 1
:PROPERTIES:
:EXPORT_FILE_NAME: terran1
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "Terran 1")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC

** RS1
:PROPERTIES:
:EXPORT_FILE_NAME: rs1
:END:

#+BEGIN_SRC emacs-lisp :results silent :exports results
  (setq rocket "RS1")
  (counts-for-rocket rocket)
#+END_SRC

Până în prezent, racheta src_emacs-lisp[:results value raw]{rocket} a fost lansată de src_emacs-lisp[:results value raw]{(nth 0 (counts-for-rocket rocket))} ori, din care src_emacs-lisp[:results value raw]{(nth 1 (counts-for-rocket rocket))} lansări au eșuat.

#+BEGIN_SRC emacs-lisp :results raw :exports results
  (get-rocket 3 rocket 0 2 3 5 6 8 12 13)
#+END_SRC


* Materiale diverse
:PROPERTIES:
:EXPORT_HUGO_SECTION: m
:END:


;; This part should be left at the end of the document.
;; Old Bulletins are already exported as Markdown files,
;; so it makes little sense to export them every single time
;; (it will just make the export time longer without a real gain).
;; Uncomment this if you REALLY want to re-export old Bulletins.
; #+INCLUDE: "old-buls.org"
