** Lansări 2022
:PROPERTIES:
:EXPORT_FILE_NAME: 2022
:EXPORT_TITLE: Lansări orbitale 2022
:END:

În anul 2022, au avut loc un total de src_emacs-lisp[:results value raw]{2022-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2022-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2022")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2022" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2021
:PROPERTIES:
:EXPORT_FILE_NAME: 2021
:EXPORT_TITLE: Lansări orbitale 2021
:END:

În anul 2021, au avut loc un total de src_emacs-lisp[:results value raw]{2021-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2021-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2021")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2021" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2020
:PROPERTIES:
:EXPORT_FILE_NAME: 2020
:EXPORT_TITLE: Lansări orbitale 2020
:END:

În anul 2020, au avut loc un total de src_emacs-lisp[:results value raw]{2020-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2020-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2020")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2020" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2019
:PROPERTIES:
:EXPORT_FILE_NAME: 2019
:EXPORT_TITLE: Lansări orbitale 2019
:END:

În anul 2019, au avut loc un total de src_emacs-lisp[:results value raw]{2019-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2019-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2019")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2019" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2018
:PROPERTIES:
:EXPORT_FILE_NAME: 2018
:EXPORT_TITLE: Lansări orbitale 2018
:END:

În anul 2018, au avut loc un total de src_emacs-lisp[:results value raw]{2018-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2018-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2018")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2018" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2017
:PROPERTIES:
:EXPORT_FILE_NAME: 2017
:EXPORT_TITLE: Lansări orbitale 2017
:END:

În anul 2017, au avut loc un total de src_emacs-lisp[:results value raw]{2017-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2017-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2017")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2017" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2016
:PROPERTIES:
:EXPORT_FILE_NAME: 2016
:EXPORT_TITLE: Lansări orbitale 2016
:END:

În anul 2016, au avut loc un total de src_emacs-lisp[:results value raw]{2016-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2016-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2016")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2016" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2015
:PROPERTIES:
:EXPORT_FILE_NAME: 2015
:EXPORT_TITLE: Lansări orbitale 2015
:END:

În anul 2015, au avut loc un total de src_emacs-lisp[:results value raw]{2015-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2015-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2015")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2015" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2014
:PROPERTIES:
:EXPORT_FILE_NAME: 2014
:EXPORT_TITLE: Lansări orbitale 2014
:END:

În anul 2014, au avut loc un total de src_emacs-lisp[:results value raw]{2014-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2014-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2014")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2014" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2013
:PROPERTIES:
:EXPORT_FILE_NAME: 2013
:EXPORT_TITLE: Lansări orbitale 2013
:END:

În anul 2013, au avut loc un total de src_emacs-lisp[:results value raw]{2013-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2013-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2013")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2013" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2012
:PROPERTIES:
:EXPORT_FILE_NAME: 2012
:EXPORT_TITLE: Lansări orbitale 2012
:END:

În anul 2012, au avut loc un total de src_emacs-lisp[:results value raw]{2012-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2012-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2012")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2012" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2011
:PROPERTIES:
:EXPORT_FILE_NAME: 2011
:EXPORT_TITLE: Lansări orbitale 2011
:END:

În anul 2011, au avut loc un total de src_emacs-lisp[:results value raw]{2011-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2011-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2011")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2011" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2010
:PROPERTIES:
:EXPORT_FILE_NAME: 2010
:EXPORT_TITLE: Lansări orbitale 2010
:END:

În anul 2010, au avut loc un total de src_emacs-lisp[:results value raw]{2010-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2010-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2010")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2010" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2009
:PROPERTIES:
:EXPORT_FILE_NAME: 2009
:EXPORT_TITLE: Lansări orbitale 2009
:END:

În anul 2009, au avut loc un total de src_emacs-lisp[:results value raw]{2009-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2009-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2009")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2009" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2008
:PROPERTIES:
:EXPORT_FILE_NAME: 2008
:EXPORT_TITLE: Lansări orbitale 2008
:END:

În anul 2008, au avut loc un total de src_emacs-lisp[:results value raw]{2008-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2008-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2008")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2008" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2007
:PROPERTIES:
:EXPORT_FILE_NAME: 2007
:EXPORT_TITLE: Lansări orbitale 2007
:END:

În anul 2007, au avut loc un total de src_emacs-lisp[:results value raw]{2007-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2007-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2007")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2007" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2006
:PROPERTIES:
:EXPORT_FILE_NAME: 2006
:EXPORT_TITLE: Lansări orbitale 2006
:END:

În anul 2006, au avut loc un total de src_emacs-lisp[:results value raw]{2006-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2006-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2006")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2006" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2005
:PROPERTIES:
:EXPORT_FILE_NAME: 2005
:EXPORT_TITLE: Lansări orbitale 2005
:END:

În anul 2005, au avut loc un total de src_emacs-lisp[:results value raw]{2005-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2005-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2005")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2005" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2004
:PROPERTIES:
:EXPORT_FILE_NAME: 2004
:EXPORT_TITLE: Lansări orbitale 2004
:END:

În anul 2004, au avut loc un total de src_emacs-lisp[:results value raw]{2004-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2004-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2004")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2004" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2003
:PROPERTIES:
:EXPORT_FILE_NAME: 2003
:EXPORT_TITLE: Lansări orbitale 2003
:END:

În anul 2003, au avut loc un total de src_emacs-lisp[:results value raw]{2003-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2003-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2003")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2003" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2002
:PROPERTIES:
:EXPORT_FILE_NAME: 2002
:EXPORT_TITLE: Lansări orbitale 2002
:END:

În anul 2002, au avut loc un total de src_emacs-lisp[:results value raw]{2002-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2002-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2002")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2002" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2001
:PROPERTIES:
:EXPORT_FILE_NAME: 2001
:EXPORT_TITLE: Lansări orbitale 2001
:END:

În anul 2001, au avut loc un total de src_emacs-lisp[:results value raw]{2001-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2001-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2001")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2001" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 2000
:PROPERTIES:
:EXPORT_FILE_NAME: 2000
:EXPORT_TITLE: Lansări orbitale 2000
:END:

În anul 2000, au avut loc un total de src_emacs-lisp[:results value raw]{2000-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{2000-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "2000")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "2000" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1999
:PROPERTIES:
:EXPORT_FILE_NAME: 1999
:EXPORT_TITLE: Lansări orbitale 1999
:END:

În anul 1999, au avut loc un total de src_emacs-lisp[:results value raw]{1999-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1999-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1999")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1999" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1998
:PROPERTIES:
:EXPORT_FILE_NAME: 1998
:EXPORT_TITLE: Lansări orbitale 1998
:END:

În anul 1998, au avut loc un total de src_emacs-lisp[:results value raw]{1998-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1998-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1998")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1998" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1997
:PROPERTIES:
:EXPORT_FILE_NAME: 1997
:EXPORT_TITLE: Lansări orbitale 1997
:END:

În anul 1997, au avut loc un total de src_emacs-lisp[:results value raw]{1997-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1997-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1997")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1997" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1996
:PROPERTIES:
:EXPORT_FILE_NAME: 1996
:EXPORT_TITLE: Lansări orbitale 1996
:END:

În anul 1996, au avut loc un total de src_emacs-lisp[:results value raw]{1996-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1996-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1996")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1996" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1995
:PROPERTIES:
:EXPORT_FILE_NAME: 1995
:EXPORT_TITLE: Lansări orbitale 1995
:END:

În anul 1995, au avut loc un total de src_emacs-lisp[:results value raw]{1995-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1995-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1995")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1995" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1994
:PROPERTIES:
:EXPORT_FILE_NAME: 1994
:EXPORT_TITLE: Lansări orbitale 1994
:END:

În anul 1994, au avut loc un total de src_emacs-lisp[:results value raw]{1994-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1994-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1994")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1994" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1993
:PROPERTIES:
:EXPORT_FILE_NAME: 1993
:EXPORT_TITLE: Lansări orbitale 1993
:END:

În anul 1993, au avut loc un total de src_emacs-lisp[:results value raw]{1993-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1993-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1993")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1993" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1992
:PROPERTIES:
:EXPORT_FILE_NAME: 1992
:EXPORT_TITLE: Lansări orbitale 1992
:END:

În anul 1992, au avut loc un total de src_emacs-lisp[:results value raw]{1992-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1992-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1992")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1992" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1991
:PROPERTIES:
:EXPORT_FILE_NAME: 1991
:EXPORT_TITLE: Lansări orbitale 1991
:END:

În anul 1991, au avut loc un total de src_emacs-lisp[:results value raw]{1991-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1991-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1991")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1991" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1990
:PROPERTIES:
:EXPORT_FILE_NAME: 1990
:EXPORT_TITLE: Lansări orbitale 1990
:END:

În anul 1990, au avut loc un total de src_emacs-lisp[:results value raw]{1990-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1990-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1990")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1990" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1989
:PROPERTIES:
:EXPORT_FILE_NAME: 1989
:EXPORT_TITLE: Lansări orbitale 1989
:END:

În anul 1989, au avut loc un total de src_emacs-lisp[:results value raw]{1989-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1989-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1989")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1989" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1988
:PROPERTIES:
:EXPORT_FILE_NAME: 1988
:EXPORT_TITLE: Lansări orbitale 1988
:END:

În anul 1988, au avut loc un total de src_emacs-lisp[:results value raw]{1988-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1988-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1988")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1988" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1987
:PROPERTIES:
:EXPORT_FILE_NAME: 1987
:EXPORT_TITLE: Lansări orbitale 1987
:END:

În anul 1987, au avut loc un total de src_emacs-lisp[:results value raw]{1987-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1987-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1987")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1987" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1986
:PROPERTIES:
:EXPORT_FILE_NAME: 1986
:EXPORT_TITLE: Lansări orbitale 1986
:END:

În anul 1986, au avut loc un total de src_emacs-lisp[:results value raw]{1986-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1986-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1986")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1986" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1985
:PROPERTIES:
:EXPORT_FILE_NAME: 1985
:EXPORT_TITLE: Lansări orbitale 1985
:END:

În anul 1985, au avut loc un total de src_emacs-lisp[:results value raw]{1985-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1985-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1985")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1985" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1984
:PROPERTIES:
:EXPORT_FILE_NAME: 1984
:EXPORT_TITLE: Lansări orbitale 1984
:END:

În anul 1984, au avut loc un total de src_emacs-lisp[:results value raw]{1984-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1984-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1984")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1984" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1983
:PROPERTIES:
:EXPORT_FILE_NAME: 1983
:EXPORT_TITLE: Lansări orbitale 1983
:END:

În anul 1983, au avut loc un total de src_emacs-lisp[:results value raw]{1983-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1983-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1983")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1983" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1982
:PROPERTIES:
:EXPORT_FILE_NAME: 1982
:EXPORT_TITLE: Lansări orbitale 1982
:END:

În anul 1982, au avut loc un total de src_emacs-lisp[:results value raw]{1982-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1982-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1982")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1982" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1981
:PROPERTIES:
:EXPORT_FILE_NAME: 1981
:EXPORT_TITLE: Lansări orbitale 1981
:END:

În anul 1981, au avut loc un total de src_emacs-lisp[:results value raw]{1981-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1981-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1981")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1981" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1980
:PROPERTIES:
:EXPORT_FILE_NAME: 1980
:EXPORT_TITLE: Lansări orbitale 1980
:END:

În anul 1980, au avut loc un total de src_emacs-lisp[:results value raw]{1980-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1980-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1980")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1980" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1979
:PROPERTIES:
:EXPORT_FILE_NAME: 1979
:EXPORT_TITLE: Lansări orbitale 1979
:END:

În anul 1979, au avut loc un total de src_emacs-lisp[:results value raw]{1979-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1979-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1979")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1979" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1978
:PROPERTIES:
:EXPORT_FILE_NAME: 1978
:EXPORT_TITLE: Lansări orbitale 1978
:END:

În anul 1978, au avut loc un total de src_emacs-lisp[:results value raw]{1978-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1978-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1978")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1978" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1977
:PROPERTIES:
:EXPORT_FILE_NAME: 1977
:EXPORT_TITLE: Lansări orbitale 1977
:END:

În anul 1977, au avut loc un total de src_emacs-lisp[:results value raw]{1977-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1977-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1977")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1977" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1976
:PROPERTIES:
:EXPORT_FILE_NAME: 1976
:EXPORT_TITLE: Lansări orbitale 1976
:END:

În anul 1976, au avut loc un total de src_emacs-lisp[:results value raw]{1976-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1976-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1976")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1976" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1975
:PROPERTIES:
:EXPORT_FILE_NAME: 1975
:EXPORT_TITLE: Lansări orbitale 1975
:END:

În anul 1975, au avut loc un total de src_emacs-lisp[:results value raw]{1975-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1975-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1975")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1975" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1974
:PROPERTIES:
:EXPORT_FILE_NAME: 1974
:EXPORT_TITLE: Lansări orbitale 1974
:END:

În anul 1974, au avut loc un total de src_emacs-lisp[:results value raw]{1974-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1974-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1974")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1974" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1973
:PROPERTIES:
:EXPORT_FILE_NAME: 1973
:EXPORT_TITLE: Lansări orbitale 1973
:END:

În anul 1973, au avut loc un total de src_emacs-lisp[:results value raw]{1973-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1973-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1973")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1973" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1972
:PROPERTIES:
:EXPORT_FILE_NAME: 1972
:EXPORT_TITLE: Lansări orbitale 1972
:END:

În anul 1972, au avut loc un total de src_emacs-lisp[:results value raw]{1972-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1972-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1972")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1972" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1971
:PROPERTIES:
:EXPORT_FILE_NAME: 1971
:EXPORT_TITLE: Lansări orbitale 1971
:END:

În anul 1971, au avut loc un total de src_emacs-lisp[:results value raw]{1971-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1971-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1971")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1971" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1970
:PROPERTIES:
:EXPORT_FILE_NAME: 1970
:EXPORT_TITLE: Lansări orbitale 1970
:END:

În anul 1970, au avut loc un total de src_emacs-lisp[:results value raw]{1970-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1970-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1970")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1970" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1969
:PROPERTIES:
:EXPORT_FILE_NAME: 1969
:EXPORT_TITLE: Lansări orbitale 1969
:END:

În anul 1969, au avut loc un total de src_emacs-lisp[:results value raw]{1969-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1969-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1969")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1969" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1968
:PROPERTIES:
:EXPORT_FILE_NAME: 1968
:EXPORT_TITLE: Lansări orbitale 1968
:END:

În anul 1968, au avut loc un total de src_emacs-lisp[:results value raw]{1968-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1968-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1968")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1968" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1967
:PROPERTIES:
:EXPORT_FILE_NAME: 1967
:EXPORT_TITLE: Lansări orbitale 1967
:END:

În anul 1967, au avut loc un total de src_emacs-lisp[:results value raw]{1967-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1967-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1967")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1967" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1966
:PROPERTIES:
:EXPORT_FILE_NAME: 1966
:EXPORT_TITLE: Lansări orbitale 1966
:END:

În anul 1966, au avut loc un total de src_emacs-lisp[:results value raw]{1966-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1966-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1966")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1966" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1965
:PROPERTIES:
:EXPORT_FILE_NAME: 1965
:EXPORT_TITLE: Lansări orbitale 1965
:END:

În anul 1965, au avut loc un total de src_emacs-lisp[:results value raw]{1965-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1965-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1965")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1965" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1964
:PROPERTIES:
:EXPORT_FILE_NAME: 1964
:EXPORT_TITLE: Lansări orbitale 1964
:END:

În anul 1964, au avut loc un total de src_emacs-lisp[:results value raw]{1964-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1964-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1964")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1964" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1963
:PROPERTIES:
:EXPORT_FILE_NAME: 1963
:EXPORT_TITLE: Lansări orbitale 1963
:END:

În anul 1963, au avut loc un total de src_emacs-lisp[:results value raw]{1963-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1963-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1963")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1963" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1962
:PROPERTIES:
:EXPORT_FILE_NAME: 1962
:EXPORT_TITLE: Lansări orbitale 1962
:END:

În anul 1962, au avut loc un total de src_emacs-lisp[:results value raw]{1962-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1962-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1962")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1962" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1961
:PROPERTIES:
:EXPORT_FILE_NAME: 1961
:EXPORT_TITLE: Lansări orbitale 1961
:END:

În anul 1961, au avut loc un total de src_emacs-lisp[:results value raw]{1961-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1961-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1961")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1961" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1960
:PROPERTIES:
:EXPORT_FILE_NAME: 1960
:EXPORT_TITLE: Lansări orbitale 1960
:END:

În anul 1960, au avut loc un total de src_emacs-lisp[:results value raw]{1960-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1960-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1960")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1960" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1959
:PROPERTIES:
:EXPORT_FILE_NAME: 1959
:EXPORT_TITLE: Lansări orbitale 1959
:END:

În anul 1959, au avut loc un total de src_emacs-lisp[:results value raw]{1959-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1959-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1959")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1959" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1958
:PROPERTIES:
:EXPORT_FILE_NAME: 1958
:EXPORT_TITLE: Lansări orbitale 1958
:END:

În anul 1958, au avut loc un total de src_emacs-lisp[:results value raw]{1958-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1958-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1958")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1958" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC

** Lansări 1957
:PROPERTIES:
:EXPORT_FILE_NAME: 1957
:EXPORT_TITLE: Lansări orbitale 1957
:END:

În anul 1957, au avut loc un total de src_emacs-lisp[:results value raw]{1957-total} tentative de lansări orbitale, din care src_emacs-lisp[:results value raw]{1957-failures} eșecuri.

#+BEGIN_SRC emacs-lisp :results raw :exports results
(table-launches-year "1957")
#+END_SRC

#+BEGIN_SRC emacs-lisp :results raw :exports results
(list-launches-for-year "1957" 0 2 3 5 6 8 12 13 '("ID" "Dată (UTC)" "Lansator" "Serie" "Misiune" "Centru" "TR" "R"))
#+END_SRC